### ISSUE TITLE
Cannot download update on first installation

### ISSUE THREAD

**Issue by AllevatoreAnonimo** [Special-Niewbie/HandleOS#4]
During the first installation, it was not possible to download the update from 2.0 to 2.7 due to the lack of an internet browser.
I suggest using programmes such as wget to download this update or use the command via powershell Invoke-WebRequest due to the native lack of being able to download files from the web.

Platform used: Steam Deck LCD
Installation iso used: HandleOS_23H2v2.iso

**Comment by Special-Niewbie** [comment]
> During the first installation, it was not possible to download the update from 2.0 to 2.7 due to the lack of an internet browser. I suggest using programmes such as wget to download this update or use the command via powershell Invoke-WebRequest due to the native lack of being able to download files from the web.
> 
> Platform used: Steam Deck LCD Installation iso used: HandleOS_23H2v2.iso

Thank you for pointing that out. For the ISO, I didn't want to include pre-installed programs, especially browsers, as they involve user privacy. I figured that anyone installing HandleOS could find other ways to install what they needed. However, I appreciate your suggestion, and I may consider including something in the next ISO release that allows users to see what they're downloading with complete transparency!

**Comment by AllevatoreAnonimo** [comment]
I am waiting for the new version for this feature. I am closing the post.
